### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Kongledyret** [cmd430/vue-dashboard#4]
Hi! 
I've added all the IP's and keys(plex/tmdb etc) but it doesn't show anything. And changed from conf-template to conf. 

Do I need to rebuild or something?

**Comment by cmd430** [comment]
are you using a webserver to server the page i.e Nginx? if so make sure you have php_fpm installed for use with Nginx

**Comment by cmd430** [comment]
I'm closing this issue feel free to reopen it if you are still experiencing problems

**Comment by cmd430** [comment]
I was just thinking about this issue and I realized I'm a massive idiot, you need to do the following before putting on you're web server

*Assuming you are already in the vue-dashboard directory and have [node 10+](https://nodejs.org/en/) installed
```bash
npm i
npm run build
``` 

This will create a directory `dist` in the root of the project the contents of that directory should then be put on the PHP enabled web server
